/* plan-seed.js — the exact 2019 ዓ/ም ዕቅድ from
 * "የህፃናት_እና_ታዳጊዎች_ክፍል_የ_2019_ዓ_ም_እቅድ.docx", seeded on first load.
 * ዋና ግብ: "በክርስቲያናዊ እምነት፣በመልካም ስነምግባር፣በፍቅርና በአገልግሎት የበለፀጉ ልጆችን ማፍራት" */
window.HK_PLAN_SEED = [
  {
    no: 1,
    subUnit: '',
    title: 'መረጃ ማደራጀት',
    details: 'ፎርም ማዘጋጀት; እንዲሞሉ ማድረግ',
    outcome: '',
    indicator: 'በፐርሰንት',
    target: '80%',
    timing: 'ከመስከረም-ህዳር',
    executor: 'ህፃናት ክፍል ከ የሰው ሀብት አስተዳደር ክፍል ጋር በመተባበር',
    budget: '2000',
    weight: '',
    category: 'main',
  },
  {
    no: 2,
    subUnit: '',
    title: 'መንፈሳዊ ፊልም እና መንፈሳዊ ጨዋታ ማሳየት',
    details: 'ታሪኮችን መፈለግ; የታሪክ አባት ማዘጋጀት; መንፈሳዊ ፊልም ማሳየት; መንፈሳዊ ጨዋታ ማዘጋጀት',
    outcome: '',
    indicator: 'በፐርሰንት',
    target: '80%',
    timing: 'ከመስከረም-ነሀሴ',
    executor: 'ህፃናት ክፍል',
    budget: '',
    weight: '',
    category: 'main',
  },
  {
    no: 3,
    subUnit: '',
    title: 'የቁርባን መርሀግብር ማዘጋጀት',
    details: 'ጊዜ መመደብ; ቦታ ማዘጋጀት; ትምህርት መስጠት; ከንስሐ አባት ጋር ማገናኘት',
    outcome: '',
    indicator: 'በቁጥር',
    target: '4',
    timing: 'ጥቅምት 22, ጥር 30, መጋቢት 29, ግንቦት 1',
    executor: 'ህፃናት ክፍል',
    budget: '',
    weight: '',
    category: 'main',
  },
  {
    no: 4,
    subUnit: '',
    title: 'የጠፉ አባላትን መፈለግ',
    details: 'አቴንዳስ መከታተል; ደውሎ ምክንያት መጠየቅ; ደብዳቤ መላክ; ቤት ድረስ መሄድ',
    outcome: '',
    indicator: 'በፐርሰንት',
    target: '70%',
    timing: 'ከመስከረም-ነሀሴ',
    executor: 'ህፃናት ክፍል',
    budget: '500',
    weight: '',
    category: 'main',
  },
  {
    no: 5,
    subUnit: '',
    title: 'ስርዓተ ትምህርት እና የአብነት ትምህርት በተገቢ ሁኔታ መስጠቱን መቆጣጠር',
    details: 'ትምህርት መሰጠቱን መቆጣጠር; ስልጠና መሰጠቱን መቆጣጠር; መምህራንን መገምገም; የተማሩትን ትምህርት ተግባራዊ ልምምድ በመስጠት መከታተል; መምህራንን ማስመደብ; ጊዜ ማመቻቸት',
    outcome: '',
    indicator: 'በፐርሰንት',
    target: '90%',
    timing: 'ከመስከረም-ነሀሴ',
    executor: 'ህፃናት ክፍል ከ ትምህርት እና ስልጠና ክፍል ጋር በመተባበር',
    budget: '',
    weight: '',
    category: 'main',
  },
  {
    no: 6,
    subUnit: '',
    title: 'መዝሙር እና ኪነጥበብ ስራዎችን በተገቢ ሁኔታ መስጠቱን መቆጣጠር',
    details: 'የአመቱን መዝሙራት በወቅታቸው መጠናቱን መቆጣጠር; የንግስ ወረቦች መጠናቱን መቆጣጠር; የኪነጥበብ ስራዎች በወቅታቸው እየተሰሩ መሆኑን መቆጣጠር',
    outcome: '',
    indicator: 'በፐርሰንት',
    target: '90%',
    timing: 'ከመስከረም-ነሀሴ',
    executor: 'ህፃናት ክፍል ከ ዜማ እና ስነጥበብ ክፍል ጋር በመተባበር',
    budget: '',
    weight: '',
    category: 'main',
  },
  {
    no: 7,
    subUnit: '',
    title: 'አባላትን በ ቤተሰብ ማደራጀት',
    details: 'አባት እና እናት መመደብ; በወር አንዴ እንዲሰበሰቡ ማድረግ',
    outcome: '',
    indicator: 'በፐርሰንት',
    target: '80%',
    timing: 'ከህዳር-የካቲት',
    executor: 'ህፃናት ክፍል ከሰው ሀብት አስተዳደር ክፍል ጋር በመተባበር',
    budget: '',
    weight: '',
    category: 'main',
  },
  {
    no: 8,
    subUnit: '',
    title: 'መንፈሳዊ ቦታዎችን እንዲጎበኙ ሁኔታዎችን ማመቻቸት',
    details: 'ከሚመለከተው ክፍል ጋር በመሆን መንፈሳዊ ቦታዎችን እንዲጎበኙ ማድረግ',
    outcome: '',
    indicator: 'በቁጥር',
    target: '2',
    timing: 'የካቲት 21, ሐምሌ 25',
    executor: 'ህፃናት ክፍል ከ መረጃ እና የውስጥ ግንኙነት ክፍል ጋር በመተባበር',
    budget: '1000',
    weight: '',
    category: 'main',
  },
  {
    no: 9,
    subUnit: '',
    title: 'ከወላጆች ጋር ትስስር መፍጠር',
    details: 'ኮሚውኒኬሽን ቡክ እንዲዘጋጅ ማድረግ; በየ 3 ወሩ የውይይት መርሀግብር ማዘጋጀት; የ ስነምግባር እና የዕለት ተዕለት ለውጣቸውን መከታተል',
    outcome: '',
    indicator: 'በፐርሰንት',
    target: '80%',
    timing: 'ከመስከረም-ነሀሴ',
    executor: 'ህፃናት ክፍል ከመርሀግብር እና ጉባዔያት ክፍል ጋር በመተባበር',
    budget: '1500',
    weight: '',
    category: 'main',
  },
  {
    no: 10,
    subUnit: '',
    title: 'የተለያዩ መርሀግብሮችን ማዘጋጀት',
    details: 'የውይይት መድረኮችን ማዘጋጀት; የልደት፣የሰንበት ት/ቤቱን የልደት መርሀግብር ማዘጋጀት; ለመርሀግብሩ ሚሆኑ ስራዎችን የሚመለከተው ክፍል ማዘጋጀቱን መቆጣጠር; ንግስ ወይም መርሀግብር ካለፈ በኋላ ግምገማ በማድረግ የመፍትሄ ሀሳቦችን ማስቀመጥ',
    outcome: '',
    indicator: 'በቁጥር',
    target: '5',
    timing: 'መስከረም 23, ታህሳስ 25, ጥር 9, ነሀሴ 23, ነሀሴ 29',
    executor: 'ህፃናት ክፍል ከ መርሀግብርና ጉባዔያት እና ከዜማናስነጥበብ ክፍል ጋር በመተባበር',
    budget: '3000',
    weight: '',
    category: 'main',
  },
  {
    no: 11,
    subUnit: '',
    title: 'ወርሀዊ መዋጮ መሰብሰብ',
    details: 'ከህፃናት መሰብሰብ; ከአባላት መሰብሰብ; የተሰበሰበውን ብር ለሚመለከተው ክፍል ማስረከብ',
    outcome: '',
    indicator: 'በቁጥር',
    target: '12',
    timing: '12 ጊዜ',
    executor: 'ህፃናት ክፍል ከ ሂሳብና ንብረት ክፍል ጋር በመተባበር',
    budget: '',
    weight: '',
    category: 'main',
  },
  {
    no: 12,
    subUnit: '',
    title: 'ስብሰባ ማድረግ',
    details: 'ከአባላት ጋር በመነጋገር በወሩ መጨረሻ መሰብሰብ',
    outcome: '',
    indicator: 'በፐርሰንት',
    target: '80%',
    timing: 'ከመስከረም-ነሀሴ',
    executor: 'ህፃናት ክፍል',
    budget: '',
    weight: '',
    category: 'main',
  },
  {
    no: 13,
    subUnit: '',
    title: 'ልምድ ልውውጥ ማድረግ',
    details: 'ቦታ መምረጥ; ደብዳቤ መላክ',
    outcome: '',
    indicator: 'በቁጥር',
    target: '1',
    timing: 'የካቲት 28',
    executor: 'ህፃናት ክፍል',
    budget: '200',
    weight: '',
    category: 'main',
  },
  {
    no: 14,
    subUnit: '',
    title: 'የ 2020 ዕቅድ ማቀድ',
    details: 'የ2019 እቅድን መሰረት በማድረግ ማቀድ; ክፍተቶችን ለመድፈን መፍትሄ በመፈለግ ማቀድ',
    outcome: '',
    indicator: 'በቁጥር',
    target: '1',
    timing: 'ነሀሴ',
    executor: 'ህፃናት ክፍል',
    budget: '',
    weight: '',
    category: 'main',
  },
];
